---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: pasw-automation
- name: pivnet-pasw
- name: pivnet-winfs-injector
run:
  path: pasw-automation/tasks/build-injected-pasw/task.sh
outputs:
- name: pasw-injected
