---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:

inputs:
  - name: pasw-automation
  - name: pasw-injected

run:
  path: pasw-automation/tasks/upload-injected-pasw/task.sh
